Repository CommunityPro/Practice-Contribution, pull requests merged in 2022-01, with the labels that each got.

#19 Add important links
  README.md
Labels: documentation, status: completed

#20 [Add profile] -> [Melford Birakor]
  Contributors.md
Labels: add user profile

#22 [Add Profile] -> [Adaeze Ndupu]
  Contributors.md
Labels: add user profile

#25 [Add profile] -> [Mike]
  Contributors.md
Labels: add user profile

#27 Fix numbering
  Contributors.md
Labels: bug, status: completed

#32 [add-tuedon] -> [Tuedon Tuoyo]
  Contributors.md
Labels: add user profile

#39 [Add profile] -> [David Edu]
  Contributors.md
Labels: add user profile

#41 Ogbeidebest
  Contributors.md
Labels: add user profile

#45 Align profile in table
  Contributors.md
Labels: bug, add user profile

#42 Add Benedict Okafor
  Contributors.md
Labels: add user profile

#44 [Add profile] -> [Mustapha Olawale]
  Contributors.md
Labels: add user profile

#48 this fixes and closes issue #46
  Contributors.md
Labels: bug, status: work in progress

#52 Add removed profile
  Contributors.md
Labels: bug

#51 [Add Contributor Profile] -> [Franklin Ohaegbulam]
  Contributors.md
Labels: add user profile

#47 Update Contributors.md
  Contributors.md
Labels: duplicate, add user profile, status: work in progress

#54 Remove text error
  Contributors.md
Labels: bug

#57 Add Charles Ejiegbu
  Contributors.md
Labels: add user profile

#60 fix blurry image
  Contributors.md
Labels: status: completed

#62 [Add Profile] -> [Williams Samuel]
  Contributors.md
Labels: add user profile

#58 Add Ayomide Bamigboye
  Contributors.md
Labels: add user profile
